name: Docker Build and Deploy

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
      - master

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/citrusi_image_scraper:${{ github.sha }} .
      
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/citrusi_image_scraper:${{ github.sha }}

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SERVER_PORT }}  # Add this if your SSH server uses a non-standard port
        script_timeout: 300s  # Set the timeout for the script
        script: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/citrusi_image_scraper:${{ github.sha }}
          docker stop citrusi_image_scraper || true
          docker rm citrusi_image_scraper || true
          docker run --name citrusi_image_scraper -d -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/citrusi_image_scraper:${{ github.sha }}